
package es.udc.ws.app.client.service.soap.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EventoProviderService", targetNamespace = "http://soap.ws.udc.es/", wsdlLocation = "file:/C:/software/ws-app/ws-app/ws-app-service/target/generated-sources/wsdl/EventoProviderService.wsdl")
public class EventoProviderService
    extends Service
{

    private final static URL EVENTOPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException EVENTOPROVIDERSERVICE_EXCEPTION;
    private final static QName EVENTOPROVIDERSERVICE_QNAME = new QName("http://soap.ws.udc.es/", "EventoProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/software/ws-app/ws-app/ws-app-service/target/generated-sources/wsdl/EventoProviderService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTOPROVIDERSERVICE_WSDL_LOCATION = url;
        EVENTOPROVIDERSERVICE_EXCEPTION = e;
    }

    public EventoProviderService() {
        super(__getWsdlLocation(), EVENTOPROVIDERSERVICE_QNAME);
    }

    public EventoProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTOPROVIDERSERVICE_QNAME, features);
    }

    public EventoProviderService(URL wsdlLocation) {
        super(wsdlLocation, EVENTOPROVIDERSERVICE_QNAME);
    }

    public EventoProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTOPROVIDERSERVICE_QNAME, features);
    }

    public EventoProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventoProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EventoProvider
     */
    @WebEndpoint(name = "EventoProviderPort")
    public EventoProvider getEventoProviderPort() {
        return super.getPort(new QName("http://soap.ws.udc.es/", "EventoProviderPort"), EventoProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EventoProvider
     */
    @WebEndpoint(name = "EventoProviderPort")
    public EventoProvider getEventoProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.udc.es/", "EventoProviderPort"), EventoProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTOPROVIDERSERVICE_EXCEPTION!= null) {
            throw EVENTOPROVIDERSERVICE_EXCEPTION;
        }
        return EVENTOPROVIDERSERVICE_WSDL_LOCATION;
    }

}
